### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-191-troiak#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
7) Відомо, що з серпня 2021 року GitHub-сервер пропонує PAT 
для процесу клонування Private GitHub-репозиторіїв. 
Поясніть, будь ласка, чому так було зроблено?

**Comment by ktry1** [comment]
На відміну від клонування публічних репозиторіїв, клонування приватних репозиторій потребує додаткових кроків у формі аутентифікації користувача. 

Починаючи з серпня 2021 року Github прибрав можливість аутентифікації у Git з використанням юзернейму і пароля через проблеми з безпекою такої форми авторизації. Через це використання personal access token, або ssh ключів стало необхідним для клонування приватних репозиторіїв. 

У випадку використання HTTPS для клонування PAT є необхідним для успішного виконання операції. Додатковий комфорт для користувача надається через можливість зберегти PAT як дефолтний для усіх HTTPS операцій у Git клієнті.

Джерела:
https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
